#!/bin/bash
#
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --mem=8000M
#SBATCH --gres=gpu:t4:2
#SBATCH --account=def-somebody

##
## note that this is meant to be submitted using sbatch
##
if [ $( expr $(hostname) : ".*login.*" ) -gt 0 ]
then
	echo 'The `hostname` appears to be '`hostname`
	echo "Are you accidentally running the job on the login node?" >&2
	exit 1
fi



ENVDIR=""

# If an argument is given, it is the name of the environment directory to use,
# otherwise set the environment directory to a standard name
if [ $# -gt 0 ] ; then
	ENVDIR="$1"
else
	ENVDIR=/home/${USER}/TF-CIS6060-environment
fi


# We must REDO the module loading before accessing our saved environment
module load StdEnv/2020
module load python/3.8.2
module load scipy-stack/2020b


# Now we can load our saved environment
source ${ENVDIR}/bin/activate

# Change to the directory where we expect to do our work
cd /home/${USER}/cis6060


python TF-run-MNIST-withplot.py

echo "DONE"
